# Generated by Django 3.0 on 2020-02-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200218_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
