# Generated by Django 3.0 on 2020-02-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200218_0149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearsectiondegreeschool',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
    ]
