# Generated by Django 3.0 on 2020-02-18 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_icon'),
        ('api', '0007_auto_20200219_0456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='yearsectiondegreeschool',
            unique_together={('school', 'degree', 'section', 'year', 'sy')},
        ),
    ]
